### ISSUE TITLE
Stopwatch respawn behavior

### ISSUE THREAD

**Issue by Glitchfinder** [mod-kitchen/hs-next#13]
Stopwatch respawn behavior appears to be different compared to the old version. This should be looked into.

**Comment by Iryn-Styl** [comment]
From some testing it appears that stopwatches only reset when you leave to another map screen and return. No amount of walking or dying has made them reset for me.

**Comment by Glitchfinder** [comment]
Turns out it was the fact that we split cooldown and active period into separate variables and only decremented one of the two.
