### ISSUE TITLE
Character Sprite incorrectly renders underneath otherworld tiles and other animated sprites during movement.

### ISSUE THREAD

**Issue by Iryn-Styl** [mod-kitchen/hs-next#29]
![image](https://github.com/mod-kitchen/hs-next/assets/154085803/d28e8b42-6bea-42bd-b8d7-c92aaaeccda2)

**Comment by Iryn-Styl** [comment]
This also happens with purple portals, perhaps it is because the tiles in question are animated/can have an animation triggered.

**Comment by Glitchfinder** [comment]
On a technical level this is because the player character is just another object, and objects are z-sorted by their height and y coordinate. Works great right up until an object is intended to be part of the ground layer, such as here. This affects every object that you can stand on top of.
