### ISSUE TITLE
Accessing Sanctuary core via the dragon's portal doesn't seem to activate the walls dropping or portals activating within the core. 

### ISSUE THREAD

**Issue by HellaVonFreyja** [mod-kitchen/hs-next#39]
Mostly added here as a... redundant coverage in case randomizer ever gets to be a thing, otherwise this is such a lowest low priority

**Comment by Glitchfinder** [comment]
This is working as intended. The core is only meant to be unlocked via the portal in the otherworld, and so access via the dragon's portal will be resolved during the mapping pass that flips the dragon's portal the proper way around.
