### ISSUE TITLE
Mismatch between interaction indicator visuals and behaviour

### ISSUE THREAD

**Issue by SiriusAshling** [mod-kitchen/hs-next#58]
If you move towards an interactible object, but haven't arrived on the target tile yet, an indicator to interact already shows, but pressing interact doesn't yet work.

**Comment by Glitchfinder** [comment]
This behavior is in line with other behaviors in the game (enemy popups, item shop price popups, etc.) and is working as intended. While it would be possible to change the interactive object pip to only reveal itself once the player completes their movement and can activate objects, this results in a situation where actively moving players will only see the interaction pip for a single frame before their movement begins again, which would be a suboptimal experience compared to seeing the pip before they are capable of interacting with the relevant object.
